-- Production Triage Toolkit -- sample workplace-booking schema.
--
-- This models a mid-size company's room-booking and facilities system: sites, rooms,
-- employees, badges, bookings, badge scans, facility requests, and a calendar-sync job.
--
-- DELIBERATE WEAKNESSES. Three constraints a textbook schema would have are missing on
-- purpose, because they are the constraints real high-write systems most often lack, and
-- their absence is what lets the corresponding data-integrity problem exist at all:
--
--   1. bookings.room_id and bookings.employee_id have NO foreign key.   -> lets DI001 exist
--   2. bookings has NO CHECK (ends_at > starts_at).                     -> lets DI005 exist
--   3. bookings.external_event_id has NO UNIQUE constraint.             -> lets DI007 exist
--
-- Each of the three runbooks (DI001, DI005, DI007) prescribes adding the missing
-- constraint as the permanent fix. The checks find the drift; the runbooks stop it
-- recurring. See docs/schema-notes.md.

BEGIN;

DROP TABLE IF EXISTS badge_scans, facility_requests, bookings, badges, employees, rooms, sites, sync_job_runs CASCADE;

CREATE TABLE sites (
    site_id     integer     PRIMARY KEY,
    name        text        NOT NULL,
    city        text        NOT NULL,
    timezone    text        NOT NULL DEFAULT 'America/Chicago',
    is_active   boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE sites IS 'Physical offices.';

CREATE TABLE rooms (
    room_id           integer     PRIMARY KEY,
    site_id           integer     NOT NULL REFERENCES sites(site_id),
    name              text        NOT NULL,
    floor             smallint    NOT NULL,
    capacity          smallint    NOT NULL CHECK (capacity > 0),
    is_active         boolean     NOT NULL DEFAULT true,
    decommissioned_at timestamptz
);
COMMENT ON TABLE rooms IS 'Bookable meeting rooms. is_active=false means decommissioned.';

CREATE TABLE employees (
    employee_id   integer     PRIMARY KEY,
    full_name     text        NOT NULL,
    email         text        NOT NULL UNIQUE,
    home_site_id  integer     REFERENCES sites(site_id),
    status        text        NOT NULL CHECK (status IN ('active','terminated','on_leave')),
    hired_on      date        NOT NULL,
    terminated_at timestamptz
);
COMMENT ON TABLE employees IS 'Staff directory, fed from the HR system.';

CREATE TABLE badges (
    badge_id       integer     PRIMARY KEY,
    employee_id    integer     NOT NULL REFERENCES employees(employee_id),
    badge_number   text        NOT NULL UNIQUE,
    is_active      boolean     NOT NULL DEFAULT true,
    issued_at      timestamptz NOT NULL,
    deactivated_at timestamptz
);
COMMENT ON TABLE badges IS 'Physical access badges. Deactivation is driven by an HR feed that can fail silently.';

-- No FK on room_id / employee_id, and no CHECK on the time range. See header.
CREATE TABLE bookings (
    booking_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id           integer     NOT NULL,
    employee_id       integer     NOT NULL,
    starts_at         timestamptz NOT NULL,
    ends_at           timestamptz NOT NULL,
    attendee_count    smallint    NOT NULL DEFAULT 1,
    status            text        NOT NULL CHECK (status IN ('confirmed','tentative','cancelled')),
    source            text        NOT NULL CHECK (source IN ('web','mobile','calendar_sync')),
    external_event_id text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE bookings IS 'The hot table. Grows to 10M rows in the benchmark dataset.';
COMMENT ON COLUMN bookings.external_event_id IS 'Idempotency key from the external calendar. Not unique -- that is DI007.';

CREATE TABLE badge_scans (
    scan_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge_id   integer     NOT NULL,
    site_id    integer     NOT NULL,
    scanned_at timestamptz NOT NULL,
    result     text        NOT NULL CHECK (result IN ('granted','denied'))
);
COMMENT ON TABLE badge_scans IS 'Door-reader events. Used to show whether a ghost badge is actually being used.';

CREATE TABLE facility_requests (
    request_id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         integer     NOT NULL,
    room_id         integer,
    opened_by       integer     NOT NULL,
    category        text        NOT NULL CHECK (category IN ('av','cleaning','hvac','furniture','security')),
    priority        text        NOT NULL CHECK (priority IN ('p1','p2','p3')),
    status          text        NOT NULL CHECK (status IN ('open','in_progress','resolved','cancelled')),
    opened_at       timestamptz NOT NULL,
    acknowledged_at timestamptz,
    resolved_at     timestamptz
);
COMMENT ON TABLE facility_requests IS 'Tickets against a site or room. SLA by priority: p1 4h, p2 24h, p3 72h.';

CREATE TABLE sync_job_runs (
    run_id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       text        NOT NULL,
    started_at     timestamptz NOT NULL,
    finished_at    timestamptz,
    status         text        NOT NULL CHECK (status IN ('running','succeeded','failed')),
    heartbeat_at   timestamptz,
    rows_processed bigint      NOT NULL DEFAULT 0,
    error_message  text
);
COMMENT ON TABLE sync_job_runs IS 'One row per run of the calendar-sync job. A run stuck in status=running is the classic silent failure.';

COMMIT;
